const stacks = [[],[],[]];
const discards = [[],[],[]];

const deck = [
    {number: 1,
    ability: 'park'},
    {number: 2,
    ability: 'park'},
    {number: 4,
    ability: 'park'},
    {number: 5,
    ability: 'park'},
    {number: 5,
    ability: 'park'},
    {number: 6,
    ability: 'park'},
    {number: 7,
    ability: 'park'},
    {number: 7,
    ability: 'park'},
    {number: 8,
    ability: 'park'},
    {number: 8,
    ability: 'park'},
    {number: 9,
    ability: 'park'},
    {number: 9,
    ability: 'park'},
    {number: 10,
    ability: 'park'},
    {number: 11,
    ability: 'park'},
    {number: 11,
    ability: 'park'},
    {number: 12,
    ability: 'park'},
    {number: 14,
    ability: 'park'},
    {number: 15,
    ability: 'park'},
    {number: 1,
    ability: 'stock_exchange'},
    {number: 2,
    ability: 'stock_exchange'},
    {number: 4,
    ability: 'stock_exchange'},
    {number: 5,
    ability: 'stock_exchange'},
    {number: 5,
    ability: 'stock_exchange'},
    {number: 6,
    ability: 'stock_exchange'},
    {number: 7,
    ability: 'stock_exchange'},
    {number: 7,
    ability: 'stock_exchange'},
    {number: 8,
    ability: 'stock_exchange'},
    {number: 8,
    ability: 'stock_exchange'},
    {number: 9,
    ability: 'stock_exchange'},
    {number: 9,
    ability: 'stock_exchange'},
    {number: 10,
    ability: 'stock_exchange'},
    {number: 11,
    ability: 'stock_exchange'},
    {number: 11,
    ability: 'stock_exchange'},
    {number: 12,
    ability: 'stock_exchange'},
    {number: 14,
    ability: 'stock_exchange'},
    {number: 15,
    ability: 'stock_exchange'},
    {number: 1,
    ability: 'fence'},
    {number: 2,
    ability: 'fence'},
    {number: 3,
    ability: 'fence'},
    {number: 5,
    ability: 'fence'},
    {number: 5,
    ability: 'fence'},
    {number: 6,
    ability: 'fence'},
    {number: 6,
    ability: 'fence'},
    {number: 7,
    ability: 'fence'},
    {number: 8,
    ability: 'fence'},
    {number: 8,
    ability: 'fence'},
    {number: 9,
    ability: 'fence'},
    {number: 10,
    ability: 'fence'},
    {number: 10,
    ability: 'fence'},
    {number: 11,
    ability: 'fence'},
    {number: 11,
    ability: 'fence'},
    {number: 13,
    ability: 'fence'},
    {number: 14,
    ability: 'fence'},
    {number: 15,
    ability: 'fence'},
    {number: 3,
    ability: 'pool'},
    {number: 4,
    ability: 'pool'},
    {number: 6,
    ability: 'pool'},
    {number: 7,
    ability: 'pool'},
    {number: 8,
    ability: 'pool'},
    {number: 9,
    ability: 'pool'},
    {number: 10,
    ability: 'pool'},
    {number: 12,
    ability: 'pool'},
    {number: 13,
    ability: 'pool'},
    {number: 3,
    ability: 'biz'},
    {number: 4,
    ability: 'biz'},
    {number: 6,
    ability: 'biz'},
    {number: 7,
    ability: 'biz'},
    {number: 8,
    ability: 'biz'},
    {number: 9,
    ability: 'biz'},
    {number: 10,
    ability: 'biz'},
    {number: 12,
    ability: 'biz'},
    {number: 13,
    ability: 'biz'},
    {number: 3,
    ability: 'temp_agency'},
    {number: 4,
    ability: 'temp_agency'},
    {number: 6,
    ability: 'temp_agency'},
    {number: 7,
    ability: 'temp_agency'},
    {number: 8,
    ability: 'temp_agency'},
    {number: 9,
    ability: 'temp_agency'},
    {number: 10,
    ability: 'temp_agency'},
    {number: 12,
    ability: 'temp_agency'},
    {number: 13,
    ability: 'temp_agency'}

]
function shuffle(deck){ 
    var m = deck.length, t, i;
    while (m) {
    i = Math.floor(Math.random() * m--);
    t = deck[m];
    deck[m] = deck[i];
    deck[i] = t;
    }
    return deck;
    }


function deal(deck){
    for(let i = 0; i < deck.length; i++){
        for (let j = 0; j < stacks.length; j++){
            let card = deck.shift();
            stacks[j].unshift(card);
        }
    }
        
    }

shuffle(deck);
console.log(deck);
deal(deck);
console.log(stacks);
// console.log(stacks);
